language: php

php:
  - 7.2
  - 7.3

install:
  - composer self-update
  - composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache/files
